# Generated by Django 4.2.5 on 2023-09-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_id",
            field=models.IntegerField(),
        ),
    ]
